### PR TITLE
Feature: add support for named args

### PR DESCRIPTION
**Pull request by jdguzman**

### CODE REVIEW

**Comment by JustinAiken** [comment]
I like it!  I'll try to figure out the listen thing today.

**Comment by JustinAiken** [comment]
@jdguzman - I fixed the listen issue with e4889bb768644ae742cdc890b980fe1885845d66, can you try rebasing your commits against `master`?

**Comment by jdguzman** [comment]
Sure I'll do that here in a while.

**Comment by jdguzman** [comment]
@JustinAiken I rebased and the Listen issue is gone but I wasn't didn't see that you were still supporting 1.9.3.  The `**` operator is a Ruby 2 feature.

**Comment by JustinAiken** [comment]
> @JustinAiken I rebased and the Listen issue is gone

Hooray!

>  I didn't see that you were still supporting 1.9.3. The ** operator is a Ruby 2 feature.

Eh, figured I might as well add it to the matrix since we didn't have anything breaking it, but I think I'd rather just kill 1.9.3 support - it barely works with Rails 4.x anyways.  

I'll merge this and cut a release today!

**Comment by JustinAiken** [comment]
These changes are released as part of [v0.3.0](https://github.com/JustinAiken/active_scheduler/releases/tag/v0.3.0)... thanks for the contribution!

**Comment by jdguzman** [comment]
@JustinAiken Thanks for the merge 👍.  I noticed you removed activesupport, `symbolize_keys` is part of activesupport so that will break the gem outside of a rails/activesupport environment, won't it?  I can change that to not use `symbolize_keys` if you would like.

**Comment by JustinAiken** [comment]
Oh haha, I guess activesupport is pulled in by activejob anyways... no worries, I'll edit the docs to reflect that.

**Pull request merged**
